-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.plot
(
    "number" smallint NOT NULL,
    surface numeric NOT NULL,
    name character varying(20) NOT NULL,
    location character varying(20) NOT NULL,
    CONSTRAINT plot_number_pk PRIMARY KEY ("number"),
    CONSTRAINT number_unique UNIQUE ("number")
);

CREATE TABLE IF NOT EXISTS public.spread
(
    fertilizer_id uuid NOT NULL,
    plot_number smallint NOT NULL,
    date date NOT NULL,
    spread_quantity numeric NOT NULL
);

CREATE TABLE IF NOT EXISTS public.date
(
    date date NOT NULL,
	CONSTRAINT date_unique UNIQUE (date)
);

CREATE TABLE IF NOT EXISTS public.fertilizer
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    unit character varying(20) NOT NULL,
    name character varying(20) NOT NULL,
    CONSTRAINT fertilizer_id_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.own
(
    fertilizer_id uuid NOT NULL,
    element_code character varying(5) NOT NULL,
    value numeric NOT NULL
);

CREATE TABLE IF NOT EXISTS public.chemical_element
(
    code character varying(5) NOT NULL,
    unit character varying(20) NOT NULL,
    element_label character varying(20) NOT NULL,
    CONSTRAINT element_code_pk PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.unit
(
    unit character varying(20) NOT NULL,
    CONSTRAINT unit_pk PRIMARY KEY (unit)
);

CREATE TABLE IF NOT EXISTS public.production
(
    code smallint NOT NULL,
    unit character varying(20) NOT NULL,
    name character varying(20) NOT NULL,
    CONSTRAINT production_code_pk PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.culture
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    plot_number smallint NOT NULL,
    production_code smallint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    quantity numeric NOT NULL,
    CONSTRAINT culture_id_pk PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.spread
    ADD CONSTRAINT plot_number_fk FOREIGN KEY (plot_number)
    REFERENCES public.plot ("number") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.spread
    ADD CONSTRAINT fertilizer_id_fk FOREIGN KEY (fertilizer_id)
    REFERENCES public.fertilizer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.spread
    ADD CONSTRAINT date_pk FOREIGN KEY (date)
    REFERENCES public.date (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fertilizer
    ADD CONSTRAINT fertilizer_unit_fk FOREIGN KEY (unit)
    REFERENCES public.unit (unit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.own
    ADD CONSTRAINT own_fertilizer_id_fk FOREIGN KEY (fertilizer_id)
    REFERENCES public.fertilizer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.own
    ADD CONSTRAINT own_element_code_fk FOREIGN KEY (element_code)
    REFERENCES public.chemical_element (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.chemical_element
    ADD CONSTRAINT chemical_unit_fk FOREIGN KEY (unit)
    REFERENCES public.unit (unit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.production
    ADD CONSTRAINT production_unit_fk FOREIGN KEY (unit)
    REFERENCES public.unit (unit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.culture
    ADD CONSTRAINT culture_production_code_fk FOREIGN KEY (production_code)
    REFERENCES public.production (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.culture
    ADD CONSTRAINT culture_plot_number_fk FOREIGN KEY (plot_number)
    REFERENCES public.plot ("number") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;